### ISSUE TITLE
Access denied to 'CelebA-HQ-1024.pt' file and no 'morph_list.txt' in folders !!!

### ISSUE THREAD

**Issue by zero-suger** [Aravinda27/MLSD-GAN#1]
Hi ~

Thank you such a hard work on this project. 

Currently we are trying to reimplement you code but while accessing to 'CelebA-HQ-1024.pt' file (weight file) and 'morph_list.txt' file, we are getting some troubles even when we are trying to access the LINK as you provided in GitHub and the files in the GitHub repo the folder structure. 

Please could you share the new link or the repo which we can find the 'CelebA-HQ-1024.pt' and 'morph_list.txt' files ?

Thank you (:

**Comment by Aravinda27** [comment]
Hello,

I think CelebA-HQ-1024.pt is removed from their original repo.

**Comment by zero-suger** [comment]
> Hello,
> 
> I think CelebA-HQ-1024.pt is removed from their original repo.

Thank you, I will try to contact with them. But what about 'morph_list.txt' file ? I cannot find this file ? Please could you share some information about this ?

**Comment by Aravinda27** [comment]
Hello,

morph_list is the list of of images from FRGC dataset. You need to download FRGC dataset and create segregate the passport quality images. More details are in the paper. Please go through it.
